Add many more helper methods to player
solid-software/flutter_vlc_player pull request #104
Opened 2020-09-09 19:54 UTC by alr2413

This PR Only implemented and tested on Android.
Features:
1) fix black screen issue on android devices when rotation changes.
2) get list of embedded audio tracks (also changed some names to be more like vlc conventions)
3) get list of embedded subtitle tracks (also changed some names to be more like vlc conventions)
4) get list of embedded video sections
5) support local and network videos (isLocalVideo parameter) and subtitles (isLocalSubtitle parameter)
6) added casting ability to external display
7) added autoplay & looping options
8) set/get subtitle delay, set/get audio delay
9) and more .... :)

2020-09-09 19:59 UTC, alr2413 commented
I've tried to add IOS implementation of this changes, but it's not clear to me how to do that.
I hope someone implement that.

2020-09-10 05:56 UTC, topilski commented
Nice work @alr2413

2020-09-10 06:17 UTC, csongorkeller commented
Big thanks for fixing it 👍

2020-09-10 09:24 UTC, csongorkeller commented
Can you point on @alr2413 which part fixes the android black screen issue? So I can quickly check that on my end as well. THanks in advance

2020-09-10 11:00 UTC, alr2413 commented
> Can you point on @alr2413 which part fixes the android black screen issue? So I can quickly check that on my end as well. THanks in advance

The part of code that was in "onSurfaceTextureAvailable" method, was moved to an Runnable closure.

2020-09-10 15:41 UTC, topilski commented
@alr2413 how can I see swift part not ready?

2020-09-10 17:28 UTC, alr2413 commented
> @alr2413 how can I see swift part not ready?

See What? As I mentioned "This PR Only implemented and tested on Android."

2020-09-11 12:41 UTC, solid-software commented
Thanks for your work @alr2413! We hope that somebody can help with the iOS part to make it complete. Also do you mind resolving all of the conflicts?

2020-09-11 13:25 UTC, mitchross reviewed
I will do iOS Part..

2020-09-11 13:25 UTC, mitchross commented on example/lib/main.dart
> +//            SizedBox(
dont commit commented out code.

2020-09-11 18:02 UTC, alr2413 reviewed
> Thanks for your work @alr2413! We hope that somebody can help with the iOS part to make it complete. Also do you mind resolving all of the conflicts?

As I mentioned, some changes are based on vlc convention (like "audioTrack" instead of "sound"). That's why I proposed to use major revision for the next release.

2020-09-11 20:04 UTC, mitchross commented
hey @alr2413 do you wanna to add me as a contributor to your repo of this fork? I can help resolve conflicts and complete iOS part

2020-09-12 18:01 UTC, csongorkeller commented
@alr2413 I've checked in emulator, and the rotation doesn't work for me with the example app in the repo. You also tested with the example app?

2020-09-12 18:23 UTC, alr2413 commented
> @alr2413 I've checked in emulator, and the rotation doesn't work for me with the example app in the repo. You also tested with the example app?

What do you mean "the rotation doesn't work"? 
Yes, I've tested on my real android device and it's working.

2020-09-12 18:54 UTC, csongorkeller commented
> > @alr2413 I've checked in emulator, and the rotation doesn't work for me with the example app in the repo. You also tested with the example app?
> 
> 
> 
> What do you mean "the rotation doesn't work"? 
> 
> Yes, I've tested on my real android device and it's working.

Well,
I've tried to run the example app in the project. And the player doesn't start at all on my end. And when I rotate the screen, I got just a white background instead of the player object. So basically the whole player don't really work for me, and therefore the rotation also doesnt. Can you upload the project hete, where you run the player in landscape? So I can check with my environment too. 
I hope you can help me with this. Thanks in advance, and many thanks for fixing vlc for all of the flutter enthusiasts.

2020-09-12 20:45 UTC, mitchross commented
@csongorkeller Please hold tight. Im actively working on helping out @alr2413. Im working on his code right now...

2020-09-12 22:03 UTC, csongorkeller commented
Thank you @mitchross  
Can you please verify the android part as well after you're done with your modifications? Would you please also update the example app too, so I could see how to use both android and ios? 
Thanks a lot in advance

2020-09-14 10:40 UTC, csongorkeller commented
android seems like working. Good job @alr2413. But I have an issue with disposing the player. If I want to change the video, I dispose the player with the method you've implemented, but for the new player, I got a black screen without any playing. Do you have any idea what I'm doing wrong?

2020-09-14 13:13 UTC, mitchross commented
@csongorkeller The change url is working in example app. "onPressed: () => _videoViewController.setStreamUrl(changeUrl),"

Can you be a bit more specific, I can look deeper.

2020-09-14 17:56 UTC, alr2413 commented
Yes, if you dispose and release the player then you need to reinitialize it
again.
As mentioned by @Mitch <mitchross09@gmail.com> you should use the
"setStreamUrl" method for that purpose.

On Mon, Sep 14, 2020 at 5:43 PM Mitch Ross <notifications@github.com> wrote:

> @csongorkeller <https://github.com/csongorkeller> The change url is
> working in example app. "onPressed: () =>
> _videoViewController.setStreamUrl(changeUrl),"
>
> Can you be a bit more specific, I can look deeper.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/solid-software/flutter_vlc_player/pull/104#issuecomment-692043413>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACNFZM6VXL3NFYM43JY4ZN3SFYJJNANCNFSM4RDEHN2A>
> .
>

2020-09-15 04:55 UTC, zxl777 commented
_controller.dispose(); can not work.

Type (MissingPluginException)
No implementation found for method dispose on channel flutter_video_plugin/getVideoView_0

 ```
 @override
  void deactivate() {
    _controller.dispose();
    playerInitialized = false;
    super.deactivate();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }
```

2020-09-15 06:13 UTC, alr2413 commented
I've tested the "dispose" method, and I got no exception.
Maybe the problem is somewhere else, if you can, share your code to check
it.

On Tue, Sep 15, 2020 at 9:25 AM Sky <notifications@github.com> wrote:

> _controller.dispose(); can not work.
>
> Type (MissingPluginException)
> No implementation found for method dispose on channel
> flutter_video_plugin/getVideoView_0
>
> @override
>  void deactivate() {
>    _controller.dispose();
>    playerInitialized = false;
>    super.deactivate();
>  }
>
>  @override
>  void dispose() {
>    _controller.dispose();
>    super.dispose();
>  }
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/solid-software/flutter_vlc_player/pull/104#issuecomment-692463622>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACNFZM7ZWGRNDYDWDQXW5L3SF3XUDANCNFSM4RDEHN2A>
> .
>

2020-09-15 08:21 UTC, zxl777 commented
Thank you for your prompt reply,
Replace the main.dart by this code.
Then tap the camera button to cause the "dispose" exception.

```
import 'dart:async';
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:flutter_vlc_player/flutter_vlc_player.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => new _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(home: MyAppScaffold());
  }
}

class MyAppScaffold extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => MyAppScaffoldState();
}

class MyAppScaffoldState extends State<MyAppScaffold> {
  Uint8List image;

  String initUrl =
      "http://samples.mplayerhq.hu/MPEG-4/embedded_subs/1Video_2Audio_2SUBs_timed_text_streams_.mp4";

//  String initUrl = "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4";
//  String initUrl = "/storage/emulated/0/Download/Test.mp4";
//  String initUrl = "/sdcard/Download/Test.mp4";
  String initUrl2 =
      "http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_30fps_normal.mp4";

  String changeUrl =
      "http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_30fps_normal.mp4";

  var hide = false;

  VlcPlayerController _videoViewController;
  VlcPlayerController _videoViewController2;
  bool isPlaying = true;
  double sliderValue = 0.0;
  double currentPlayerTime = 0;
  double volumeValue = 100;

  @override
  void initState() {
    _videoViewController = new VlcPlayerController(onInit: () {
      _videoViewController.play();
    });
    _videoViewController.addListener(() {
      setState(() {});
    });

    _videoViewController2 = new VlcPlayerController(onInit: () {
      _videoViewController2.play();
    });
    _videoViewController2.addListener(() {
      setState(() {});
    });

    Timer.periodic(Duration(seconds: 1), (Timer timer) {
      String state = _videoViewController.playingState.toString();
      if (this.mounted) {
        setState(() {
          if (state == "PlayingState.PLAYING" &&
              sliderValue < _videoViewController.duration.inSeconds) {
            sliderValue = _videoViewController.position.inSeconds.toDouble();
          }
        });
      }
    });

    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: const Text('Plugin example app'),
      ),
      floatingActionButton: FloatingActionButton(
          child: Icon(Icons.camera),
          // onPressed: _createCameraImage,
          onPressed: () {
            setState(() {
              hide = true;
            });
          }),
      // ),
      body: hide
          ? SizedBox(
              height: 100,
            )
          : Builder(builder: (context) {
              return ListView(
                shrinkWrap: true,
                children: <Widget>[
                  SizedBox(
                    height: 250,
                    child: new VlcPlayer(
                      aspectRatio: 16 / 9,
                      url: initUrl,
                      isLocalMedia: false,
                      controller: _videoViewController,
                      // Play with vlc options
                      options: [
                        '--quiet',
//                '-vvv',
                        '--no-drop-late-frames',
                        '--no-skip-frames',
                        '--rtsp-tcp',
                      ],
                      hwAcc: HwAcc.DISABLED,
                      // or {HwAcc.AUTO, HwAcc.DECODING, HwAcc.FULL}
                      placeholder: Container(
                        height: 250.0,
                        child: Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: <Widget>[CircularProgressIndicator()],
                        ),
                      ),
                    ),
                  ),
//            SizedBox(
//              height: 360,
//              child: new VlcPlayer(
//                aspectRatio: 16 / 9,
//                url: initUrl2,
//                controller: _videoViewController2,
//                placeholder: Container(
//                  height: 250.0,
//                  child: Row(
//                    mainAxisAlignment: MainAxisAlignment.center,
//                    children: <Widget>[CircularProgressIndicator()],
//                  ),
//                ),
//              ),
//            ),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                    mainAxisSize: MainAxisSize.max,
                    children: [
                      Text("Seek"),
                      Slider(
                        activeColor: Colors.red,
                        value: sliderValue,
                        min: 0.0,
                        max: _videoViewController.duration == null
                            ? 1.0
                            : _videoViewController.duration.inSeconds
                                .toDouble(),
                        onChanged: (progress) {
                          setState(() {
                            sliderValue = progress.floor().toDouble();
                          });
                          //convert to Milliseconds since VLC requires MS to set time
                          _videoViewController
                              .setTime(sliderValue.toInt() * 1000);
                        },
                      ),
                    ],
                  ),
                  Divider(height: 1),
                  FlatButton(
                      child: isPlaying
                          ? Icon(Icons.pause)
                          : Icon(Icons.play_arrow),
                      onPressed: () => {playOrPauseVideo()}),
                  Divider(height: 1),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                    mainAxisSize: MainAxisSize.max,
                    children: [
                      Text("Volume Level"),
                      Slider(
                        min: 0,
                        max: 100,
                        value: volumeValue,
                        onChanged: (value) {
                          setState(() {
                            volumeValue = value;
                          });
                          _videoViewController.setVolume(volumeValue.toInt());
                        },
                      ),
                    ],
                  ),
                  Divider(height: 1),
                  Row(
                    children: [
                      FlatButton(
                        child: Text("Change URL"),
                        onPressed: () =>
                            _videoViewController.setStreamUrl(changeUrl),
                      ),
                      FlatButton(
                          child: Text("+speed"),
                          onPressed: () =>
                              _videoViewController.setPlaybackSpeed(2.0)),
                      FlatButton(
                          child: Text("Normal"),
                          onPressed: () =>
                              _videoViewController.setPlaybackSpeed(1)),
                      FlatButton(
                          child: Text("-speed"),
                          onPressed: () =>
                              _videoViewController.setPlaybackSpeed(0.5)),
                    ],
                  ),
                  Divider(height: 1),
                  Container(
                    padding: EdgeInsets.all(8.0),
                    child: Column(
                      children: [
                        Text("position=" +
                            _videoViewController.position.inSeconds.toString() + [...]

2020-09-15 17:36 UTC, alr2413 commented
> Thank you for your prompt reply,
> Replace the main.dart by this code.
> Then tap the camera button to cause the "dispose" exception.
> 
> ```
> import 'dart:async';
> import 'dart:typed_data';
> 
> import 'package:flutter/material.dart';
> import 'package:flutter_vlc_player/flutter_vlc_player.dart';
> 
> void main() => runApp(MyApp());
> 
> class MyApp extends StatefulWidget {
>   @override
>   _MyAppState createState() => new _MyAppState();
> }
> 
> class _MyAppState extends State<MyApp> {
>   @override
>   Widget build(BuildContext context) {
>     return new MaterialApp(home: MyAppScaffold());
>   }
> }
> 
> class MyAppScaffold extends StatefulWidget {
>   @override
>   State<StatefulWidget> createState() => MyAppScaffoldState();
> }
> 
> class MyAppScaffoldState extends State<MyAppScaffold> {
>   Uint8List image;
> 
>   String initUrl =
>       "http://samples.mplayerhq.hu/MPEG-4/embedded_subs/1Video_2Audio_2SUBs_timed_text_streams_.mp4";
> 
> //  String initUrl = "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4";
> //  String initUrl = "/storage/emulated/0/Download/Test.mp4";
> //  String initUrl = "/sdcard/Download/Test.mp4";
>   String initUrl2 =
>       "http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_30fps_normal.mp4";
> 
>   String changeUrl =
>       "http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_30fps_normal.mp4";
> 
>   var hide = false;
> 
>   VlcPlayerController _videoViewController;
>   VlcPlayerController _videoViewController2;
>   bool isPlaying = true;
>   double sliderValue = 0.0;
>   double currentPlayerTime = 0;
>   double volumeValue = 100;
> 
>   @override
>   void initState() {
>     _videoViewController = new VlcPlayerController(onInit: () {
>       _videoViewController.play();
>     });
>     _videoViewController.addListener(() {
>       setState(() {});
>     });
> 
>     _videoViewController2 = new VlcPlayerController(onInit: () {
>       _videoViewController2.play();
>     });
>     _videoViewController2.addListener(() {
>       setState(() {});
>     });
> 
>     Timer.periodic(Duration(seconds: 1), (Timer timer) {
>       String state = _videoViewController.playingState.toString();
>       if (this.mounted) {
>         setState(() {
>           if (state == "PlayingState.PLAYING" &&
>               sliderValue < _videoViewController.duration.inSeconds) {
>             sliderValue = _videoViewController.position.inSeconds.toDouble();
>           }
>         });
>       }
>     });
> 
>     super.initState();
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return new Scaffold(
>       appBar: new AppBar(
>         title: const Text('Plugin example app'),
>       ),
>       floatingActionButton: FloatingActionButton(
>           child: Icon(Icons.camera),
>           // onPressed: _createCameraImage,
>           onPressed: () {
>             setState(() {
>               hide = true;
>             });
>           }),
>       // ),
>       body: hide
>           ? SizedBox(
>               height: 100,
>             )
>           : Builder(builder: (context) {
>               return ListView(
>                 shrinkWrap: true,
>                 children: <Widget>[
>                   SizedBox(
>                     height: 250,
>                     child: new VlcPlayer(
>                       aspectRatio: 16 / 9,
>                       url: initUrl,
>                       isLocalMedia: false,
>                       controller: _videoViewController,
>                       // Play with vlc options
>                       options: [
>                         '--quiet',
> //                '-vvv',
>                         '--no-drop-late-frames',
>                         '--no-skip-frames',
>                         '--rtsp-tcp',
>                       ],
>                       hwAcc: HwAcc.DISABLED,
>                       // or {HwAcc.AUTO, HwAcc.DECODING, HwAcc.FULL}
>                       placeholder: Container(
>                         height: 250.0,
>                         child: Row(
>                           mainAxisAlignment: MainAxisAlignment.center,
>                           children: <Widget>[CircularProgressIndicator()],
>                         ),
>                       ),
>                     ),
>                   ),
> //            SizedBox(
> //              height: 360,
> //              child: new VlcPlayer(
> //                aspectRatio: 16 / 9,
> //                url: initUrl2,
> //                controller: _videoViewController2,
> //                placeholder: Container(
> //                  height: 250.0,
> //                  child: Row(
> //                    mainAxisAlignment: MainAxisAlignment.center,
> //                    children: <Widget>[CircularProgressIndicator()],
> //                  ),
> //                ),
> //              ),
> //            ),
>                   Row(
>                     mainAxisAlignment: MainAxisAlignment.spaceEvenly,
>                     mainAxisSize: MainAxisSize.max,
>                     children: [
>                       Text("Seek"),
>                       Slider(
>                         activeColor: Colors.red,
>                         value: sliderValue,
>                         min: 0.0,
>                         max: _videoViewController.duration == null
>                             ? 1.0
>                             : _videoViewController.duration.inSeconds
>                                 .toDouble(),
>                         onChanged: (progress) {
>                           setState(() {
>                             sliderValue = progress.floor().toDouble();
>                           });
>                           //convert to Milliseconds since VLC requires MS to set time
>                           _videoViewController
>                               .setTime(sliderValue.toInt() * 1000);
>                         },
>                       ),
>                     ],
>                   ),
>                   Divider(height: 1),
>                   FlatButton(
>                       child: isPlaying
>                           ? Icon(Icons.pause)
>                           : Icon(Icons.play_arrow),
>                       onPressed: () => {playOrPauseVideo()}),
>                   Divider(height: 1),
>                   Row(
>                     mainAxisAlignment: MainAxisAlignment.spaceEvenly,
>                     mainAxisSize: MainAxisSize.max,
>                     children: [
>                       Text("Volume Level"),
>                       Slider(
>                         min: 0,
>                         max: 100,
>                         value: volumeValue,
>                         onChanged: (value) {
>                           setState(() {
>                             volumeValue = value;
>                           });
>                           _videoViewController.setVolume(volumeValue.toInt());
>                         },
>                       ),
>                     ],
>                   ),
>                   Divider(height: 1),
>                   Row(
>                     children: [
>                       FlatButton(
>                         child: Text("Change URL"),
>                         onPressed: () =>
>                             _videoViewController.setStreamUrl(changeUrl),
>                       ),
>                       FlatButton(
>                           child: Text("+speed"),
>                           onPressed: () =>
>                               _videoViewController.setPlaybackSpeed(2.0)),
>                       FlatButton(
>                           child: Text("Normal"),
>                           onPressed: () =>
>                               _videoViewController.setPlaybackSpeed(1)),
>                       FlatButton(
>                           child: Text("-speed"),
>                           onPressed:  [...]

2020-09-15 23:40 UTC, zxl777 commented
> > Thank you for your prompt reply,
> > Replace the main.dart by this code.
> > Then tap the camera button to cause the "dispose" exception.
> > ```
> > import 'dart:async';
> > import 'dart:typed_data';
> > 
> > import 'package:flutter/material.dart';
> > import 'package:flutter_vlc_player/flutter_vlc_player.dart';
> > 
> > void main() => runApp(MyApp());
> > 
> > class MyApp extends StatefulWidget {
> >   @override
> >   _MyAppState createState() => new _MyAppState();
> > }
> > 
> > class _MyAppState extends State<MyApp> {
> >   @override
> >   Widget build(BuildContext context) {
> >     return new MaterialApp(home: MyAppScaffold());
> >   }
> > }
> > 
> > class MyAppScaffold extends StatefulWidget {
> >   @override
> >   State<StatefulWidget> createState() => MyAppScaffoldState();
> > }
> > 
> > class MyAppScaffoldState extends State<MyAppScaffold> {
> >   Uint8List image;
> > 
> >   String initUrl =
> >       "http://samples.mplayerhq.hu/MPEG-4/embedded_subs/1Video_2Audio_2SUBs_timed_text_streams_.mp4";
> > 
> > //  String initUrl = "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4";
> > //  String initUrl = "/storage/emulated/0/Download/Test.mp4";
> > //  String initUrl = "/sdcard/Download/Test.mp4";
> >   String initUrl2 =
> >       "http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_30fps_normal.mp4";
> > 
> >   String changeUrl =
> >       "http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_30fps_normal.mp4";
> > 
> >   var hide = false;
> > 
> >   VlcPlayerController _videoViewController;
> >   VlcPlayerController _videoViewController2;
> >   bool isPlaying = true;
> >   double sliderValue = 0.0;
> >   double currentPlayerTime = 0;
> >   double volumeValue = 100;
> > 
> >   @override
> >   void initState() {
> >     _videoViewController = new VlcPlayerController(onInit: () {
> >       _videoViewController.play();
> >     });
> >     _videoViewController.addListener(() {
> >       setState(() {});
> >     });
> > 
> >     _videoViewController2 = new VlcPlayerController(onInit: () {
> >       _videoViewController2.play();
> >     });
> >     _videoViewController2.addListener(() {
> >       setState(() {});
> >     });
> > 
> >     Timer.periodic(Duration(seconds: 1), (Timer timer) {
> >       String state = _videoViewController.playingState.toString();
> >       if (this.mounted) {
> >         setState(() {
> >           if (state == "PlayingState.PLAYING" &&
> >               sliderValue < _videoViewController.duration.inSeconds) {
> >             sliderValue = _videoViewController.position.inSeconds.toDouble();
> >           }
> >         });
> >       }
> >     });
> > 
> >     super.initState();
> >   }
> > 
> >   @override
> >   Widget build(BuildContext context) {
> >     return new Scaffold(
> >       appBar: new AppBar(
> >         title: const Text('Plugin example app'),
> >       ),
> >       floatingActionButton: FloatingActionButton(
> >           child: Icon(Icons.camera),
> >           // onPressed: _createCameraImage,
> >           onPressed: () {
> >             setState(() {
> >               hide = true;
> >             });
> >           }),
> >       // ),
> >       body: hide
> >           ? SizedBox(
> >               height: 100,
> >             )
> >           : Builder(builder: (context) {
> >               return ListView(
> >                 shrinkWrap: true,
> >                 children: <Widget>[
> >                   SizedBox(
> >                     height: 250,
> >                     child: new VlcPlayer(
> >                       aspectRatio: 16 / 9,
> >                       url: initUrl,
> >                       isLocalMedia: false,
> >                       controller: _videoViewController,
> >                       // Play with vlc options
> >                       options: [
> >                         '--quiet',
> > //                '-vvv',
> >                         '--no-drop-late-frames',
> >                         '--no-skip-frames',
> >                         '--rtsp-tcp',
> >                       ],
> >                       hwAcc: HwAcc.DISABLED,
> >                       // or {HwAcc.AUTO, HwAcc.DECODING, HwAcc.FULL}
> >                       placeholder: Container(
> >                         height: 250.0,
> >                         child: Row(
> >                           mainAxisAlignment: MainAxisAlignment.center,
> >                           children: <Widget>[CircularProgressIndicator()],
> >                         ),
> >                       ),
> >                     ),
> >                   ),
> > //            SizedBox(
> > //              height: 360,
> > //              child: new VlcPlayer(
> > //                aspectRatio: 16 / 9,
> > //                url: initUrl2,
> > //                controller: _videoViewController2,
> > //                placeholder: Container(
> > //                  height: 250.0,
> > //                  child: Row(
> > //                    mainAxisAlignment: MainAxisAlignment.center,
> > //                    children: <Widget>[CircularProgressIndicator()],
> > //                  ),
> > //                ),
> > //              ),
> > //            ),
> >                   Row(
> >                     mainAxisAlignment: MainAxisAlignment.spaceEvenly,
> >                     mainAxisSize: MainAxisSize.max,
> >                     children: [
> >                       Text("Seek"),
> >                       Slider(
> >                         activeColor: Colors.red,
> >                         value: sliderValue,
> >                         min: 0.0,
> >                         max: _videoViewController.duration == null
> >                             ? 1.0
> >                             : _videoViewController.duration.inSeconds
> >                                 .toDouble(),
> >                         onChanged: (progress) {
> >                           setState(() {
> >                             sliderValue = progress.floor().toDouble();
> >                           });
> >                           //convert to Milliseconds since VLC requires MS to set time
> >                           _videoViewController
> >                               .setTime(sliderValue.toInt() * 1000);
> >                         },
> >                       ),
> >                     ],
> >                   ),
> >                   Divider(height: 1),
> >                   FlatButton(
> >                       child: isPlaying
> >                           ? Icon(Icons.pause)
> >                           : Icon(Icons.play_arrow),
> >                       onPressed: () => {playOrPauseVideo()}),
> >                   Divider(height: 1),
> >                   Row(
> >                     mainAxisAlignment: MainAxisAlignment.spaceEvenly,
> >                     mainAxisSize: MainAxisSize.max,
> >                     children: [
> >                       Text("Volume Level"),
> >                       Slider(
> >                         min: 0,
> >                         max: 100,
> >                         value: volumeValue,
> >                         onChanged: (value) {
> >                           setState(() {
> >                             volumeValue = value;
> >                           });
> >                           _videoViewController.setVolume(volumeValue.toInt());
> >                         },
> >                       ),
> >                     ],
> >                   ),
> >                   Divider(height: 1),
> >                   Row(
> >                     children: [
> >                       FlatButton(
> >                         child: Text("Change URL"),
> >                         onPressed: () =>
> >                             _videoViewController.setStreamUrl(changeUrl),
> >                       ),
> >                       FlatButton(
> >                           child: Text("+speed"),
> >                           onPressed: ()  [...]

2020-09-16 00:06 UTC, mitchross commented
@zxl777 Im helping with iOS... ios14 broke lots of things, trying to fix.

2020-09-17 14:15 UTC, mitchross commented
Getting close on fixing casting on iOS, will have a update for this PR hopefully by tonight

2020-09-18 18:53 UTC, topilski commented
![1600455142044](https://user-images.githubusercontent.com/4686379/93634495-5d8e4800-f9f9-11ea-8061-bd1169f92104.JPEG)
Hello, that's only my machine issue?

2020-09-18 21:43 UTC, mitchross commented
@topilski that is not on the latest commit. you appear to behind.

2020-09-18 21:44 UTC, mitchross commented
@solid-software This code is ready for merge. I have reviewed it, tested it, developed on it.

I worked with @alr2413  on the side and brought in @amadeu01

2020-09-19 05:20 UTC, topilski commented
@mitchross @alr2413  @amadeu01 thank you for your work guys!

2020-09-21 06:36 UTC, alr2413 commented
Ping @solid-software,
now the code is ready to merge.

2020-09-21 07:51 UTC, solid-software requested changes
Great job @alr2413 @mitchross - I'm blown away with the changes you guys have made!

I've added couple small comments/suggestions - please take a look and let me know what you think.

I think 4.0 would be a game changer - thanks again for your work on this!

2020-09-21 07:51 UTC, solid-software commented on android/src/main/java/software/solid/fluttervlcplayer/FlutterVideoView.java
> +//                    textureView.invalidate();
Do we need this commented out part? It looks like we need to remove all of that unless it's some additional information (if so we probably need to mark it clear) - what do you think?

2020-09-21 07:51 UTC, solid-software commented on android/src/main/java/software/solid/fluttervlcplayer/FlutterVideoView.java
> +//                    if (wasPlaying)
If we don't need that anymore we can tidy up it a little bit.

2020-09-21 07:51 UTC, solid-software commented on android/src/main/java/software/solid/fluttervlcplayer/FlutterVideoView.java
> +
This seem to be not adding much of the context - should we remove it?

2020-09-21 07:51 UTC, solid-software commented on lib/flutter_vlc_player.dart
> +  Future<int> getVolume() async {
Could you please add more comments to the public methods here? As on the pub.dev it's giving lower scores for the package and it's generally would be very helpful for the users.
<img width="726" alt="image" src="https://user-images.githubusercontent.com/40825054/93743111-17eb9e00-fbf8-11ea-8686-6a93dd3e883f.png">

2020-09-21 09:24 UTC, alr2413 commented
@solid-software I've done that.

2020-09-21 13:04 UTC, mitchross commented
@solid-software After this PR is merged there is a few more clean up tasks I'll do in follow up PRs to migrate the Android Plugin to V2 https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration

2020-09-22 09:15 UTC, solid-software approved these changes
LGTM - thanks @alr2413 @mitchross !

2020-09-22 09:17 UTC, merged

2020-09-22 10:19 UTC, alr2413 commented
@solid-software, @mitchross 
I think we should review all opened issues, and close theme if they're solved.

2020-09-22 11:36 UTC, pharshdev commented
I think the major issues still are:

[A] the "player state change", when the widget is rebuilt which could be from something as simple as orientation change or calling setstate.
**Steps to reproduce:**
1) Pause the player
2) Tilt the device or press a button that calls setstate. 

**Desired state:** Video player paused.
**Observed state:** Video player starts playing.

[B] Not adhering to App lifecycle. Any video player should be auto paused when the phone screen is turned off. This plugin would infact start playing the video even when the video was paused. Needless to say, a playing video would continue playing.

[C] Player doesnt respond well to player's widget resizing dynamically. I have an app that supports PIP and when i send a running video to PIP, there's a second or two delay before the video starts re-rendering. All this while, the audio is playing fine. Although not majorly observed, this happens when orientation change too. 

It looks like we're still missing something in the native implementations as the official vlc player doesnt have these issues.

PS: You can run into these issues even with the example code.

2020-09-22 12:15 UTC, mitchross commented
@pharshdev  i'll take care of A,B,C with the Android 2.0 Plugin update migration

2020-09-22 12:29 UTC, alr2413 commented
@pharshdev , @mitchross 
Yea, the "A" situation is based on the written code.
Before I clean up code, I've "wasPlaying" variable in Runnable method to check that situation, but I don't remember why I've commented that line.