Fix memory leak issue
solid-software/flutter_vlc_player pull request #169
Opened 2021-01-29 20:23 UTC by alr2413

Recently, @mitchross and I found there are situations that all variables & objects employed in vlc_player_controller are not disposed completely.
This could cause memory leak issue. This PR is a fix for the problem.

2021-01-29 20:38 UTC, mitchross commented
I tested this in a side project. This resolves issue on Android. I tested on iOS and confirmed no issues. Pending no implementation PR feedback, this is safe to merge. @solid-software

2021-01-30 06:37 UTC, alr2413 commented
I should mention that we also have another solution to fix this issue. let's first talk about why this issue happens.

in android, we implemented the platformView class for managing the vlc player actions. when you dispose the widget on dart, the dispose method of platformView class in android is being called automatically, so all object reference in android are getting destroyed while in dart we are not aware of that. As a result, when we call controller dispose on dart, it throws exceptions that the communication platform channel does no longer exist or VLC object is null, thus some objects are not disposed properly in dart which cause the memory leak issue.

To overcome this problem, we can use the submitted PR or we can do the following:

in dart -> revert everything on dispose method to the previous state.
in android -> make the body of override dispose method empty and move all of the lines to another method and call that method to dispose all references.

By using this way, we handle the disposition process from dart side and we no longer need the isDisposed variable on android code.

Please, share you thoughts with me.
Thanks

2021-02-01 16:19 UTC, solid-yuriiprykhodko requested changes
Good catch! Memory usage indeed looks slightly smaller (~ -5MB by my measurements).
A few minor changes requested.

2021-02-01 16:19 UTC, solid-yuriiprykhodko commented on flutter_vlc_player/example/lib/single_tab.dart
> +    _controller.removeListener(() {});
This line does exactly nothing.
We can remove a listener after we've added one, and using exactly the same reference that we used when adding it.

We should also remove a similar line in `README.md` and in `multiple_tab.dart`

2021-02-01 16:19 UTC, solid-yuriiprykhodko commented on flutter_vlc_player/example/lib/multiple_tab.dart
>      for (var i = 0; i < controllers.length; i++) {
Let's use a `for-in` loop here - we don't need to use indices here.
```suggestion
        for (final controller in controllers) {
```

2021-02-01 16:19 UTC, solid-yuriiprykhodko commented on flutter_vlc_player/example/lib/single_tab.dart
> +                    ScaffoldMessenger.of(context).showSnackBar(
The `ScaffoldMessenger` breaking change hasn't been introduced into Flutter stable channel yet. Perhaps we should hold off this change until then?

2021-02-01 18:01 UTC, mitchross commented
@solid-yuriiprykhodko I tested iOS and didnt see any memory issues either. If you notice anything wrong with iOS please let me know.

2021-02-02 15:46 UTC, alr2413 commented
@solid-yuriiprykhodko, so you think this PR is ok or i should do the following instead:

```
To overcome this problem, we can use the submitted PR or we can do the following:

in dart -> revert everything on dispose method to the previous state.
in android -> make the body of override dispose method empty and move all of the lines to another method and call that method to dispose all references.
```

I'm waiting for your response?

2021-02-04 12:47 UTC, solid-yuriiprykhodko approved these changes
LGTM!

2021-02-04 12:58 UTC, merged