Added isSeekable method
solid-software/flutter_vlc_player pull request #175
Opened 2021-02-05 14:13 UTC by alr2413

in this PR, i passed the Vlc isSeekable method to the vlc controller.
Also, i fixed the example player crash when the player position is greater than its duration. This might happen for live m3u8 streams.

2021-02-08 16:24 UTC, solid-yuriiprykhodko requested changes
Looks good to me! 
Just a couple of minor codestyle changes, and we're good to merge.

2021-02-08 16:24 UTC, solid-yuriiprykhodko commented on flutter_vlc_player/android/src/main/java/software/solid/fluttervlcplayer/FlutterVlcPlayer.java
>          //
```suggestion
        if (isDisposed) {
            return;
        }
```

2021-02-08 20:03 UTC, alr2413 commented
@solid-yuriiprykhodko.
thanks for you feedback.

2021-02-09 11:37 UTC, solid-yuriiprykhodko approved these changes

2021-02-09 11:44 UTC, merged