Avoid FlutterVlcPlayerFactory new instances onAttachedToActivity
solid-software/flutter_vlc_player pull request #214
Opened 2021-03-25 05:51 UTC by GuillermoDLCO

The player works great in a Flutter application, but I ran into a problem in an Android project that uses Flutter as a module. 

Every time I started the flutter screens again, The VLC Player no longer plays the video, this was because a new instance of the FlutterVlcPlayerFactory was created in the onAttachedToActivity method, which was executed every time I opened the Flutter Engine Activity. 

This was the solution I made to avoid new instances for cases where Flutter is used as a module in a native project.

2021-03-25 16:53 UTC, solid-yuriiprykhodko commented on flutter_vlc_player/android/src/main/java/software/solid/fluttervlcplayer/FlutterVlcPlayerPlugin.java
> +        if(flutterVlcPlayerFactory == null) {
Nitpick: missing space after `if`.

```suggestion
        if (flutterVlcPlayerFactory == null) {
```

2021-03-25 16:54 UTC, solid-yuriiprykhodko requested changes
Great work pinpointing and fixing the issue!
Let's do the same for the legacy `registerWith` method. 
I'm almost sure it's not used anymore, but better safe than sorry. :)

2021-03-26 00:23 UTC, GuillermoDLCO commented on flutter_vlc_player/android/src/main/java/software/solid/fluttervlcplayer/FlutterVlcPlayerPlugin.java
> +        if(flutterVlcPlayerFactory == null) {
Done

2021-03-26 07:13 UTC, solid-yuriiprykhodko approved these changes
Looks good, thanks!

2021-03-29 08:16 UTC, merged